model:
  d_model: 1024
  head: 8
  bucket_length: 64
  rounds: 8
  dropout: 0.1
  chunk: 8
  N: 4
  d_ff: 4096
---
data:
  dataset: "music"
  path: "../Datasets/Classics/TPD"
  data_length: 8192
  vocab: [132, 131, 131, 131, 131, 131, 131]
  valid_split: 1024
---
train:
  num_workers: 8
  accumulate: 4
  lr: 0.0001
  smoothing: 0.1
  epochs: 100000000
---
log:
  path: 'logs'
