model:
  d_model: 32
  head: 8
  n_buckets: 4
  rounds: 4
  dropout: 0.1
  N: 1
  d_ff: 32
---
data:
  name: "Synthetic"
  path: None
  dataset_length: 16384
  max_data_length: 32
  data_length: 32
  vocab: 16
---
train:
  num_workers: 4
  accumulate: 8
  lr: 0.001
  smoothing: 0.1
  epochs: 10000
---
log:
  path: 'logs'
---
chkpt:
  path: 'chkpts'
