model:
  d_model: 256
  head: 8
  bucket_length: 64
  rounds: 8
  dropout: 0.1
  chunk: 8
  N: 1
  d_ff: 256
---
data:
  dataset: "synthetic"
  path: None
  dataset_length: 2048
  max_data_length: 1024
  data_length: 1024
  vocab: 128
---
train:
  num_workers: 8
  accumulate: 1
  lr: 0.001
  smoothing: 0.1
  epochs: 100000000
---
log:
  path: 'logs'
